DROP TABLE IF EXISTS occurrence_record_AD;
CREATE TABLE occurrence_record_AD SELECT * FROM occurrence_record WHERE iso_country_code='AD';
DROP TABLE IF EXISTS occurrence_record_AE;
CREATE TABLE occurrence_record_AE SELECT * FROM occurrence_record WHERE iso_country_code='AE';
DROP TABLE IF EXISTS occurrence_record_AF;
CREATE TABLE occurrence_record_AF SELECT * FROM occurrence_record WHERE iso_country_code='AF';
DROP TABLE IF EXISTS occurrence_record_AG;
CREATE TABLE occurrence_record_AG SELECT * FROM occurrence_record WHERE iso_country_code='AG';
DROP TABLE IF EXISTS occurrence_record_AI;
CREATE TABLE occurrence_record_AI SELECT * FROM occurrence_record WHERE iso_country_code='AI';
DROP TABLE IF EXISTS occurrence_record_AL;
CREATE TABLE occurrence_record_AL SELECT * FROM occurrence_record WHERE iso_country_code='AL';
DROP TABLE IF EXISTS occurrence_record_AM;
CREATE TABLE occurrence_record_AM SELECT * FROM occurrence_record WHERE iso_country_code='AM';
DROP TABLE IF EXISTS occurrence_record_AN;
CREATE TABLE occurrence_record_AN SELECT * FROM occurrence_record WHERE iso_country_code='AN';
DROP TABLE IF EXISTS occurrence_record_AO;
CREATE TABLE occurrence_record_AO SELECT * FROM occurrence_record WHERE iso_country_code='AO';
DROP TABLE IF EXISTS occurrence_record_AQ;
CREATE TABLE occurrence_record_AQ SELECT * FROM occurrence_record WHERE iso_country_code='AQ';
DROP TABLE IF EXISTS occurrence_record_AR;
CREATE TABLE occurrence_record_AR SELECT * FROM occurrence_record WHERE iso_country_code='AR';
DROP TABLE IF EXISTS occurrence_record_AS;
CREATE TABLE occurrence_record_AS SELECT * FROM occurrence_record WHERE iso_country_code='AS';
DROP TABLE IF EXISTS occurrence_record_AT;
CREATE TABLE occurrence_record_AT SELECT * FROM occurrence_record WHERE iso_country_code='AT';
DROP TABLE IF EXISTS occurrence_record_AU;
CREATE TABLE occurrence_record_AU SELECT * FROM occurrence_record WHERE iso_country_code='AU';
DROP TABLE IF EXISTS occurrence_record_AW;
CREATE TABLE occurrence_record_AW SELECT * FROM occurrence_record WHERE iso_country_code='AW';
DROP TABLE IF EXISTS occurrence_record_AX;
CREATE TABLE occurrence_record_AX SELECT * FROM occurrence_record WHERE iso_country_code='AX';
DROP TABLE IF EXISTS occurrence_record_AZ;
CREATE TABLE occurrence_record_AZ SELECT * FROM occurrence_record WHERE iso_country_code='AZ';
DROP TABLE IF EXISTS occurrence_record_BA;
CREATE TABLE occurrence_record_BA SELECT * FROM occurrence_record WHERE iso_country_code='BA';
DROP TABLE IF EXISTS occurrence_record_BB;
CREATE TABLE occurrence_record_BB SELECT * FROM occurrence_record WHERE iso_country_code='BB';
DROP TABLE IF EXISTS occurrence_record_BD;
CREATE TABLE occurrence_record_BD SELECT * FROM occurrence_record WHERE iso_country_code='BD';
DROP TABLE IF EXISTS occurrence_record_BE;
CREATE TABLE occurrence_record_BE SELECT * FROM occurrence_record WHERE iso_country_code='BE';
DROP TABLE IF EXISTS occurrence_record_BF;
CREATE TABLE occurrence_record_BF SELECT * FROM occurrence_record WHERE iso_country_code='BF';
DROP TABLE IF EXISTS occurrence_record_BG;
CREATE TABLE occurrence_record_BG SELECT * FROM occurrence_record WHERE iso_country_code='BG';
DROP TABLE IF EXISTS occurrence_record_BH;
CREATE TABLE occurrence_record_BH SELECT * FROM occurrence_record WHERE iso_country_code='BH';
DROP TABLE IF EXISTS occurrence_record_BI;
CREATE TABLE occurrence_record_BI SELECT * FROM occurrence_record WHERE iso_country_code='BI';
DROP TABLE IF EXISTS occurrence_record_BJ;
CREATE TABLE occurrence_record_BJ SELECT * FROM occurrence_record WHERE iso_country_code='BJ';
DROP TABLE IF EXISTS occurrence_record_BL;
CREATE TABLE occurrence_record_BL SELECT * FROM occurrence_record WHERE iso_country_code='BL';
DROP TABLE IF EXISTS occurrence_record_BM;
CREATE TABLE occurrence_record_BM SELECT * FROM occurrence_record WHERE iso_country_code='BM';
DROP TABLE IF EXISTS occurrence_record_BN;
CREATE TABLE occurrence_record_BN SELECT * FROM occurrence_record WHERE iso_country_code='BN';
DROP TABLE IF EXISTS occurrence_record_BO;
CREATE TABLE occurrence_record_BO SELECT * FROM occurrence_record WHERE iso_country_code='BO';
DROP TABLE IF EXISTS occurrence_record_BR;
CREATE TABLE occurrence_record_BR SELECT * FROM occurrence_record WHERE iso_country_code='BR';
DROP TABLE IF EXISTS occurrence_record_BS;
CREATE TABLE occurrence_record_BS SELECT * FROM occurrence_record WHERE iso_country_code='BS';
DROP TABLE IF EXISTS occurrence_record_BT;
CREATE TABLE occurrence_record_BT SELECT * FROM occurrence_record WHERE iso_country_code='BT';
DROP TABLE IF EXISTS occurrence_record_BV;
CREATE TABLE occurrence_record_BV SELECT * FROM occurrence_record WHERE iso_country_code='BV';
DROP TABLE IF EXISTS occurrence_record_BW;
CREATE TABLE occurrence_record_BW SELECT * FROM occurrence_record WHERE iso_country_code='BW';
DROP TABLE IF EXISTS occurrence_record_BY;
CREATE TABLE occurrence_record_BY SELECT * FROM occurrence_record WHERE iso_country_code='BY';
DROP TABLE IF EXISTS occurrence_record_BZ;
CREATE TABLE occurrence_record_BZ SELECT * FROM occurrence_record WHERE iso_country_code='BZ';
DROP TABLE IF EXISTS occurrence_record_CA;
CREATE TABLE occurrence_record_CA SELECT * FROM occurrence_record WHERE iso_country_code='CA';
DROP TABLE IF EXISTS occurrence_record_CC;
CREATE TABLE occurrence_record_CC SELECT * FROM occurrence_record WHERE iso_country_code='CC';
DROP TABLE IF EXISTS occurrence_record_CD;
CREATE TABLE occurrence_record_CD SELECT * FROM occurrence_record WHERE iso_country_code='CD';
DROP TABLE IF EXISTS occurrence_record_CF;
CREATE TABLE occurrence_record_CF SELECT * FROM occurrence_record WHERE iso_country_code='CF';
DROP TABLE IF EXISTS occurrence_record_CG;
CREATE TABLE occurrence_record_CG SELECT * FROM occurrence_record WHERE iso_country_code='CG';
DROP TABLE IF EXISTS occurrence_record_CH;
CREATE TABLE occurrence_record_CH SELECT * FROM occurrence_record WHERE iso_country_code='CH';
DROP TABLE IF EXISTS occurrence_record_CI;
CREATE TABLE occurrence_record_CI SELECT * FROM occurrence_record WHERE iso_country_code='CI';
DROP TABLE IF EXISTS occurrence_record_CK;
CREATE TABLE occurrence_record_CK SELECT * FROM occurrence_record WHERE iso_country_code='CK';
DROP TABLE IF EXISTS occurrence_record_CL;
CREATE TABLE occurrence_record_CL SELECT * FROM occurrence_record WHERE iso_country_code='CL';
DROP TABLE IF EXISTS occurrence_record_CM;
CREATE TABLE occurrence_record_CM SELECT * FROM occurrence_record WHERE iso_country_code='CM';
DROP TABLE IF EXISTS occurrence_record_CN;
CREATE TABLE occurrence_record_CN SELECT * FROM occurrence_record WHERE iso_country_code='CN';
DROP TABLE IF EXISTS occurrence_record_CO;
CREATE TABLE occurrence_record_CO SELECT * FROM occurrence_record WHERE iso_country_code='CO';
DROP TABLE IF EXISTS occurrence_record_CR;
CREATE TABLE occurrence_record_CR SELECT * FROM occurrence_record WHERE iso_country_code='CR';
DROP TABLE IF EXISTS occurrence_record_CU;
CREATE TABLE occurrence_record_CU SELECT * FROM occurrence_record WHERE iso_country_code='CU';
DROP TABLE IF EXISTS occurrence_record_CV;
CREATE TABLE occurrence_record_CV SELECT * FROM occurrence_record WHERE iso_country_code='CV';
DROP TABLE IF EXISTS occurrence_record_CX;
CREATE TABLE occurrence_record_CX SELECT * FROM occurrence_record WHERE iso_country_code='CX';
DROP TABLE IF EXISTS occurrence_record_CY;
CREATE TABLE occurrence_record_CY SELECT * FROM occurrence_record WHERE iso_country_code='CY';
DROP TABLE IF EXISTS occurrence_record_CZ;
CREATE TABLE occurrence_record_CZ SELECT * FROM occurrence_record WHERE iso_country_code='CZ';
DROP TABLE IF EXISTS occurrence_record_DE;
CREATE TABLE occurrence_record_DE SELECT * FROM occurrence_record WHERE iso_country_code='DE';
DROP TABLE IF EXISTS occurrence_record_DJ;
CREATE TABLE occurrence_record_DJ SELECT * FROM occurrence_record WHERE iso_country_code='DJ';
DROP TABLE IF EXISTS occurrence_record_DK;
CREATE TABLE occurrence_record_DK SELECT * FROM occurrence_record WHERE iso_country_code='DK';
DROP TABLE IF EXISTS occurrence_record_DM;
CREATE TABLE occurrence_record_DM SELECT * FROM occurrence_record WHERE iso_country_code='DM';
DROP TABLE IF EXISTS occurrence_record_DO;
CREATE TABLE occurrence_record_DO SELECT * FROM occurrence_record WHERE iso_country_code='DO';
DROP TABLE IF EXISTS occurrence_record_DZ;
CREATE TABLE occurrence_record_DZ SELECT * FROM occurrence_record WHERE iso_country_code='DZ';
DROP TABLE IF EXISTS occurrence_record_EC;
CREATE TABLE occurrence_record_EC SELECT * FROM occurrence_record WHERE iso_country_code='EC';
DROP TABLE IF EXISTS occurrence_record_EE;
CREATE TABLE occurrence_record_EE SELECT * FROM occurrence_record WHERE iso_country_code='EE';
DROP TABLE IF EXISTS occurrence_record_EG;
CREATE TABLE occurrence_record_EG SELECT * FROM occurrence_record WHERE iso_country_code='EG';
DROP TABLE IF EXISTS occurrence_record_EH;
CREATE TABLE occurrence_record_EH SELECT * FROM occurrence_record WHERE iso_country_code='EH';
DROP TABLE IF EXISTS occurrence_record_ER;
CREATE TABLE occurrence_record_ER SELECT * FROM occurrence_record WHERE iso_country_code='ER';
DROP TABLE IF EXISTS occurrence_record_ES;
CREATE TABLE occurrence_record_ES SELECT * FROM occurrence_record WHERE iso_country_code='ES';
DROP TABLE IF EXISTS occurrence_record_ET;
CREATE TABLE occurrence_record_ET SELECT * FROM occurrence_record WHERE iso_country_code='ET';
DROP TABLE IF EXISTS occurrence_record_FI;
CREATE TABLE occurrence_record_FI SELECT * FROM occurrence_record WHERE iso_country_code='FI';
DROP TABLE IF EXISTS occurrence_record_FJ;
CREATE TABLE occurrence_record_FJ SELECT * FROM occurrence_record WHERE iso_country_code='FJ';
DROP TABLE IF EXISTS occurrence_record_FK;
CREATE TABLE occurrence_record_FK SELECT * FROM occurrence_record WHERE iso_country_code='FK';
DROP TABLE IF EXISTS occurrence_record_FM;
CREATE TABLE occurrence_record_FM SELECT * FROM occurrence_record WHERE iso_country_code='FM';
DROP TABLE IF EXISTS occurrence_record_FO;
CREATE TABLE occurrence_record_FO SELECT * FROM occurrence_record WHERE iso_country_code='FO';
DROP TABLE IF EXISTS occurrence_record_FR;
CREATE TABLE occurrence_record_FR SELECT * FROM occurrence_record WHERE iso_country_code='FR';
DROP TABLE IF EXISTS occurrence_record_GA;
CREATE TABLE occurrence_record_GA SELECT * FROM occurrence_record WHERE iso_country_code='GA';
DROP TABLE IF EXISTS occurrence_record_GB;
CREATE TABLE occurrence_record_GB SELECT * FROM occurrence_record WHERE iso_country_code='GB';
DROP TABLE IF EXISTS occurrence_record_GD;
CREATE TABLE occurrence_record_GD SELECT * FROM occurrence_record WHERE iso_country_code='GD';
DROP TABLE IF EXISTS occurrence_record_GE;
CREATE TABLE occurrence_record_GE SELECT * FROM occurrence_record WHERE iso_country_code='GE';
DROP TABLE IF EXISTS occurrence_record_GF;
CREATE TABLE occurrence_record_GF SELECT * FROM occurrence_record WHERE iso_country_code='GF';
DROP TABLE IF EXISTS occurrence_record_GG;
CREATE TABLE occurrence_record_GG SELECT * FROM occurrence_record WHERE iso_country_code='GG';
DROP TABLE IF EXISTS occurrence_record_GH;
CREATE TABLE occurrence_record_GH SELECT * FROM occurrence_record WHERE iso_country_code='GH';
DROP TABLE IF EXISTS occurrence_record_GI;
CREATE TABLE occurrence_record_GI SELECT * FROM occurrence_record WHERE iso_country_code='GI';
DROP TABLE IF EXISTS occurrence_record_GL;
CREATE TABLE occurrence_record_GL SELECT * FROM occurrence_record WHERE iso_country_code='GL';
DROP TABLE IF EXISTS occurrence_record_GM;
CREATE TABLE occurrence_record_GM SELECT * FROM occurrence_record WHERE iso_country_code='GM';
DROP TABLE IF EXISTS occurrence_record_GN;
CREATE TABLE occurrence_record_GN SELECT * FROM occurrence_record WHERE iso_country_code='GN';
DROP TABLE IF EXISTS occurrence_record_GP;
CREATE TABLE occurrence_record_GP SELECT * FROM occurrence_record WHERE iso_country_code='GP';
DROP TABLE IF EXISTS occurrence_record_GQ;
CREATE TABLE occurrence_record_GQ SELECT * FROM occurrence_record WHERE iso_country_code='GQ';
DROP TABLE IF EXISTS occurrence_record_GR;
CREATE TABLE occurrence_record_GR SELECT * FROM occurrence_record WHERE iso_country_code='GR';
DROP TABLE IF EXISTS occurrence_record_GS;
CREATE TABLE occurrence_record_GS SELECT * FROM occurrence_record WHERE iso_country_code='GS';
DROP TABLE IF EXISTS occurrence_record_GT;
CREATE TABLE occurrence_record_GT SELECT * FROM occurrence_record WHERE iso_country_code='GT';
DROP TABLE IF EXISTS occurrence_record_GU;
CREATE TABLE occurrence_record_GU SELECT * FROM occurrence_record WHERE iso_country_code='GU';
DROP TABLE IF EXISTS occurrence_record_GW;
CREATE TABLE occurrence_record_GW SELECT * FROM occurrence_record WHERE iso_country_code='GW';
DROP TABLE IF EXISTS occurrence_record_GY;
CREATE TABLE occurrence_record_GY SELECT * FROM occurrence_record WHERE iso_country_code='GY';
DROP TABLE IF EXISTS occurrence_record_HK;
CREATE TABLE occurrence_record_HK SELECT * FROM occurrence_record WHERE iso_country_code='HK';
DROP TABLE IF EXISTS occurrence_record_HM;
CREATE TABLE occurrence_record_HM SELECT * FROM occurrence_record WHERE iso_country_code='HM';
DROP TABLE IF EXISTS occurrence_record_HN;
CREATE TABLE occurrence_record_HN SELECT * FROM occurrence_record WHERE iso_country_code='HN';
DROP TABLE IF EXISTS occurrence_record_HR;
CREATE TABLE occurrence_record_HR SELECT * FROM occurrence_record WHERE iso_country_code='HR';
DROP TABLE IF EXISTS occurrence_record_HT;
CREATE TABLE occurrence_record_HT SELECT * FROM occurrence_record WHERE iso_country_code='HT';
DROP TABLE IF EXISTS occurrence_record_HU;
CREATE TABLE occurrence_record_HU SELECT * FROM occurrence_record WHERE iso_country_code='HU';
DROP TABLE IF EXISTS occurrence_record_ID;
CREATE TABLE occurrence_record_ID SELECT * FROM occurrence_record WHERE iso_country_code='ID';
DROP TABLE IF EXISTS occurrence_record_IE;
CREATE TABLE occurrence_record_IE SELECT * FROM occurrence_record WHERE iso_country_code='IE';
DROP TABLE IF EXISTS occurrence_record_IL;
CREATE TABLE occurrence_record_IL SELECT * FROM occurrence_record WHERE iso_country_code='IL';
DROP TABLE IF EXISTS occurrence_record_IM;
CREATE TABLE occurrence_record_IM SELECT * FROM occurrence_record WHERE iso_country_code='IM';
DROP TABLE IF EXISTS occurrence_record_IN;
CREATE TABLE occurrence_record_IN SELECT * FROM occurrence_record WHERE iso_country_code='IN';
DROP TABLE IF EXISTS occurrence_record_IO;
CREATE TABLE occurrence_record_IO SELECT * FROM occurrence_record WHERE iso_country_code='IO';
DROP TABLE IF EXISTS occurrence_record_IQ;
CREATE TABLE occurrence_record_IQ SELECT * FROM occurrence_record WHERE iso_country_code='IQ';
DROP TABLE IF EXISTS occurrence_record_IR;
CREATE TABLE occurrence_record_IR SELECT * FROM occurrence_record WHERE iso_country_code='IR';
DROP TABLE IF EXISTS occurrence_record_IS;
CREATE TABLE occurrence_record_IS SELECT * FROM occurrence_record WHERE iso_country_code='IS';
DROP TABLE IF EXISTS occurrence_record_IT;
CREATE TABLE occurrence_record_IT SELECT * FROM occurrence_record WHERE iso_country_code='IT';
DROP TABLE IF EXISTS occurrence_record_JE;
CREATE TABLE occurrence_record_JE SELECT * FROM occurrence_record WHERE iso_country_code='JE';
DROP TABLE IF EXISTS occurrence_record_JM;
CREATE TABLE occurrence_record_JM SELECT * FROM occurrence_record WHERE iso_country_code='JM';
DROP TABLE IF EXISTS occurrence_record_JO;
CREATE TABLE occurrence_record_JO SELECT * FROM occurrence_record WHERE iso_country_code='JO';
DROP TABLE IF EXISTS occurrence_record_JP;
CREATE TABLE occurrence_record_JP SELECT * FROM occurrence_record WHERE iso_country_code='JP';
DROP TABLE IF EXISTS occurrence_record_KE;
CREATE TABLE occurrence_record_KE SELECT * FROM occurrence_record WHERE iso_country_code='KE';
DROP TABLE IF EXISTS occurrence_record_KG;
CREATE TABLE occurrence_record_KG SELECT * FROM occurrence_record WHERE iso_country_code='KG';
DROP TABLE IF EXISTS occurrence_record_KH;
CREATE TABLE occurrence_record_KH SELECT * FROM occurrence_record WHERE iso_country_code='KH';
DROP TABLE IF EXISTS occurrence_record_KI;
CREATE TABLE occurrence_record_KI SELECT * FROM occurrence_record WHERE iso_country_code='KI';
DROP TABLE IF EXISTS occurrence_record_KM;
CREATE TABLE occurrence_record_KM SELECT * FROM occurrence_record WHERE iso_country_code='KM';
DROP TABLE IF EXISTS occurrence_record_KN;
CREATE TABLE occurrence_record_KN SELECT * FROM occurrence_record WHERE iso_country_code='KN';
DROP TABLE IF EXISTS occurrence_record_KP;
CREATE TABLE occurrence_record_KP SELECT * FROM occurrence_record WHERE iso_country_code='KP';
DROP TABLE IF EXISTS occurrence_record_KR;
CREATE TABLE occurrence_record_KR SELECT * FROM occurrence_record WHERE iso_country_code='KR';
DROP TABLE IF EXISTS occurrence_record_KW;
CREATE TABLE occurrence_record_KW SELECT * FROM occurrence_record WHERE iso_country_code='KW';
DROP TABLE IF EXISTS occurrence_record_KY;
CREATE TABLE occurrence_record_KY SELECT * FROM occurrence_record WHERE iso_country_code='KY';
DROP TABLE IF EXISTS occurrence_record_KZ;
CREATE TABLE occurrence_record_KZ SELECT * FROM occurrence_record WHERE iso_country_code='KZ';
DROP TABLE IF EXISTS occurrence_record_LA;
CREATE TABLE occurrence_record_LA SELECT * FROM occurrence_record WHERE iso_country_code='LA';
DROP TABLE IF EXISTS occurrence_record_LB;
CREATE TABLE occurrence_record_LB SELECT * FROM occurrence_record WHERE iso_country_code='LB';
DROP TABLE IF EXISTS occurrence_record_LC;
CREATE TABLE occurrence_record_LC SELECT * FROM occurrence_record WHERE iso_country_code='LC';
DROP TABLE IF EXISTS occurrence_record_LI;
CREATE TABLE occurrence_record_LI SELECT * FROM occurrence_record WHERE iso_country_code='LI';
DROP TABLE IF EXISTS occurrence_record_LK;
CREATE TABLE occurrence_record_LK SELECT * FROM occurrence_record WHERE iso_country_code='LK';
DROP TABLE IF EXISTS occurrence_record_LR;
CREATE TABLE occurrence_record_LR SELECT * FROM occurrence_record WHERE iso_country_code='LR';
DROP TABLE IF EXISTS occurrence_record_LS;
CREATE TABLE occurrence_record_LS SELECT * FROM occurrence_record WHERE iso_country_code='LS';
DROP TABLE IF EXISTS occurrence_record_LT;
CREATE TABLE occurrence_record_LT SELECT * FROM occurrence_record WHERE iso_country_code='LT';
DROP TABLE IF EXISTS occurrence_record_LU;
CREATE TABLE occurrence_record_LU SELECT * FROM occurrence_record WHERE iso_country_code='LU';
DROP TABLE IF EXISTS occurrence_record_LV;
CREATE TABLE occurrence_record_LV SELECT * FROM occurrence_record WHERE iso_country_code='LV';
DROP TABLE IF EXISTS occurrence_record_LY;
CREATE TABLE occurrence_record_LY SELECT * FROM occurrence_record WHERE iso_country_code='LY';
DROP TABLE IF EXISTS occurrence_record_MA;
CREATE TABLE occurrence_record_MA SELECT * FROM occurrence_record WHERE iso_country_code='MA';
DROP TABLE IF EXISTS occurrence_record_MC;
CREATE TABLE occurrence_record_MC SELECT * FROM occurrence_record WHERE iso_country_code='MC';
DROP TABLE IF EXISTS occurrence_record_MD;
CREATE TABLE occurrence_record_MD SELECT * FROM occurrence_record WHERE iso_country_code='MD';
DROP TABLE IF EXISTS occurrence_record_ME;
CREATE TABLE occurrence_record_ME SELECT * FROM occurrence_record WHERE iso_country_code='ME';
DROP TABLE IF EXISTS occurrence_record_MF;
CREATE TABLE occurrence_record_MF SELECT * FROM occurrence_record WHERE iso_country_code='MF';
DROP TABLE IF EXISTS occurrence_record_MG;
CREATE TABLE occurrence_record_MG SELECT * FROM occurrence_record WHERE iso_country_code='MG';
DROP TABLE IF EXISTS occurrence_record_MH;
CREATE TABLE occurrence_record_MH SELECT * FROM occurrence_record WHERE iso_country_code='MH';
DROP TABLE IF EXISTS occurrence_record_MK;
CREATE TABLE occurrence_record_MK SELECT * FROM occurrence_record WHERE iso_country_code='MK';
DROP TABLE IF EXISTS occurrence_record_ML;
CREATE TABLE occurrence_record_ML SELECT * FROM occurrence_record WHERE iso_country_code='ML';
DROP TABLE IF EXISTS occurrence_record_MM;
CREATE TABLE occurrence_record_MM SELECT * FROM occurrence_record WHERE iso_country_code='MM';
DROP TABLE IF EXISTS occurrence_record_MN;
CREATE TABLE occurrence_record_MN SELECT * FROM occurrence_record WHERE iso_country_code='MN';
DROP TABLE IF EXISTS occurrence_record_MO;
CREATE TABLE occurrence_record_MO SELECT * FROM occurrence_record WHERE iso_country_code='MO';
DROP TABLE IF EXISTS occurrence_record_MP;
CREATE TABLE occurrence_record_MP SELECT * FROM occurrence_record WHERE iso_country_code='MP';
DROP TABLE IF EXISTS occurrence_record_MQ;
CREATE TABLE occurrence_record_MQ SELECT * FROM occurrence_record WHERE iso_country_code='MQ';
DROP TABLE IF EXISTS occurrence_record_MR;
CREATE TABLE occurrence_record_MR SELECT * FROM occurrence_record WHERE iso_country_code='MR';
DROP TABLE IF EXISTS occurrence_record_MS;
CREATE TABLE occurrence_record_MS SELECT * FROM occurrence_record WHERE iso_country_code='MS';
DROP TABLE IF EXISTS occurrence_record_MT;
CREATE TABLE occurrence_record_MT SELECT * FROM occurrence_record WHERE iso_country_code='MT';
DROP TABLE IF EXISTS occurrence_record_MU;
CREATE TABLE occurrence_record_MU SELECT * FROM occurrence_record WHERE iso_country_code='MU';
DROP TABLE IF EXISTS occurrence_record_MV;
CREATE TABLE occurrence_record_MV SELECT * FROM occurrence_record WHERE iso_country_code='MV';
DROP TABLE IF EXISTS occurrence_record_MW;
CREATE TABLE occurrence_record_MW SELECT * FROM occurrence_record WHERE iso_country_code='MW';
DROP TABLE IF EXISTS occurrence_record_MX;
CREATE TABLE occurrence_record_MX SELECT * FROM occurrence_record WHERE iso_country_code='MX';
DROP TABLE IF EXISTS occurrence_record_MY;
CREATE TABLE occurrence_record_MY SELECT * FROM occurrence_record WHERE iso_country_code='MY';
DROP TABLE IF EXISTS occurrence_record_MZ;
CREATE TABLE occurrence_record_MZ SELECT * FROM occurrence_record WHERE iso_country_code='MZ';
DROP TABLE IF EXISTS occurrence_record_NA;
CREATE TABLE occurrence_record_NA SELECT * FROM occurrence_record WHERE iso_country_code='NA';
DROP TABLE IF EXISTS occurrence_record_NC;
CREATE TABLE occurrence_record_NC SELECT * FROM occurrence_record WHERE iso_country_code='NC';
DROP TABLE IF EXISTS occurrence_record_NE;
CREATE TABLE occurrence_record_NE SELECT * FROM occurrence_record WHERE iso_country_code='NE';
DROP TABLE IF EXISTS occurrence_record_NF;
CREATE TABLE occurrence_record_NF SELECT * FROM occurrence_record WHERE iso_country_code='NF';
DROP TABLE IF EXISTS occurrence_record_NG;
CREATE TABLE occurrence_record_NG SELECT * FROM occurrence_record WHERE iso_country_code='NG';
DROP TABLE IF EXISTS occurrence_record_NI;
CREATE TABLE occurrence_record_NI SELECT * FROM occurrence_record WHERE iso_country_code='NI';
DROP TABLE IF EXISTS occurrence_record_NL;
CREATE TABLE occurrence_record_NL SELECT * FROM occurrence_record WHERE iso_country_code='NL';
DROP TABLE IF EXISTS occurrence_record_NO;
CREATE TABLE occurrence_record_NO SELECT * FROM occurrence_record WHERE iso_country_code='NO';
DROP TABLE IF EXISTS occurrence_record_NP;
CREATE TABLE occurrence_record_NP SELECT * FROM occurrence_record WHERE iso_country_code='NP';
DROP TABLE IF EXISTS occurrence_record_NR;
CREATE TABLE occurrence_record_NR SELECT * FROM occurrence_record WHERE iso_country_code='NR';
DROP TABLE IF EXISTS occurrence_record_NU;
CREATE TABLE occurrence_record_NU SELECT * FROM occurrence_record WHERE iso_country_code='NU';
DROP TABLE IF EXISTS occurrence_record_NZ;
CREATE TABLE occurrence_record_NZ SELECT * FROM occurrence_record WHERE iso_country_code='NZ';
DROP TABLE IF EXISTS occurrence_record_OM;
CREATE TABLE occurrence_record_OM SELECT * FROM occurrence_record WHERE iso_country_code='OM';
DROP TABLE IF EXISTS occurrence_record_PA;
CREATE TABLE occurrence_record_PA SELECT * FROM occurrence_record WHERE iso_country_code='PA';
DROP TABLE IF EXISTS occurrence_record_PE;
CREATE TABLE occurrence_record_PE SELECT * FROM occurrence_record WHERE iso_country_code='PE';
DROP TABLE IF EXISTS occurrence_record_PF;
CREATE TABLE occurrence_record_PF SELECT * FROM occurrence_record WHERE iso_country_code='PF';
DROP TABLE IF EXISTS occurrence_record_PG;
CREATE TABLE occurrence_record_PG SELECT * FROM occurrence_record WHERE iso_country_code='PG';
DROP TABLE IF EXISTS occurrence_record_PH;
CREATE TABLE occurrence_record_PH SELECT * FROM occurrence_record WHERE iso_country_code='PH';
DROP TABLE IF EXISTS occurrence_record_PK;
CREATE TABLE occurrence_record_PK SELECT * FROM occurrence_record WHERE iso_country_code='PK';
DROP TABLE IF EXISTS occurrence_record_PL;
CREATE TABLE occurrence_record_PL SELECT * FROM occurrence_record WHERE iso_country_code='PL';
DROP TABLE IF EXISTS occurrence_record_PM;
CREATE TABLE occurrence_record_PM SELECT * FROM occurrence_record WHERE iso_country_code='PM';
DROP TABLE IF EXISTS occurrence_record_PN;
CREATE TABLE occurrence_record_PN SELECT * FROM occurrence_record WHERE iso_country_code='PN';
DROP TABLE IF EXISTS occurrence_record_PR;
CREATE TABLE occurrence_record_PR SELECT * FROM occurrence_record WHERE iso_country_code='PR';
DROP TABLE IF EXISTS occurrence_record_PS;
CREATE TABLE occurrence_record_PS SELECT * FROM occurrence_record WHERE iso_country_code='PS';
DROP TABLE IF EXISTS occurrence_record_PT;
CREATE TABLE occurrence_record_PT SELECT * FROM occurrence_record WHERE iso_country_code='PT';
DROP TABLE IF EXISTS occurrence_record_PW;
CREATE TABLE occurrence_record_PW SELECT * FROM occurrence_record WHERE iso_country_code='PW';
DROP TABLE IF EXISTS occurrence_record_PY;
CREATE TABLE occurrence_record_PY SELECT * FROM occurrence_record WHERE iso_country_code='PY';
DROP TABLE IF EXISTS occurrence_record_QA;
CREATE TABLE occurrence_record_QA SELECT * FROM occurrence_record WHERE iso_country_code='QA';
DROP TABLE IF EXISTS occurrence_record_RE;
CREATE TABLE occurrence_record_RE SELECT * FROM occurrence_record WHERE iso_country_code='RE';
DROP TABLE IF EXISTS occurrence_record_RO;
CREATE TABLE occurrence_record_RO SELECT * FROM occurrence_record WHERE iso_country_code='RO';
DROP TABLE IF EXISTS occurrence_record_RS;
CREATE TABLE occurrence_record_RS SELECT * FROM occurrence_record WHERE iso_country_code='RS';
DROP TABLE IF EXISTS occurrence_record_RU;
CREATE TABLE occurrence_record_RU SELECT * FROM occurrence_record WHERE iso_country_code='RU';
DROP TABLE IF EXISTS occurrence_record_RW;
CREATE TABLE occurrence_record_RW SELECT * FROM occurrence_record WHERE iso_country_code='RW';
DROP TABLE IF EXISTS occurrence_record_SA;
CREATE TABLE occurrence_record_SA SELECT * FROM occurrence_record WHERE iso_country_code='SA';
DROP TABLE IF EXISTS occurrence_record_SB;
CREATE TABLE occurrence_record_SB SELECT * FROM occurrence_record WHERE iso_country_code='SB';
DROP TABLE IF EXISTS occurrence_record_SC;
CREATE TABLE occurrence_record_SC SELECT * FROM occurrence_record WHERE iso_country_code='SC';
DROP TABLE IF EXISTS occurrence_record_SD;
CREATE TABLE occurrence_record_SD SELECT * FROM occurrence_record WHERE iso_country_code='SD';
DROP TABLE IF EXISTS occurrence_record_SE;
CREATE TABLE occurrence_record_SE SELECT * FROM occurrence_record WHERE iso_country_code='SE';
DROP TABLE IF EXISTS occurrence_record_SG;
CREATE TABLE occurrence_record_SG SELECT * FROM occurrence_record WHERE iso_country_code='SG';
DROP TABLE IF EXISTS occurrence_record_SH;
CREATE TABLE occurrence_record_SH SELECT * FROM occurrence_record WHERE iso_country_code='SH';
DROP TABLE IF EXISTS occurrence_record_SI;
CREATE TABLE occurrence_record_SI SELECT * FROM occurrence_record WHERE iso_country_code='SI';
DROP TABLE IF EXISTS occurrence_record_SJ;
CREATE TABLE occurrence_record_SJ SELECT * FROM occurrence_record WHERE iso_country_code='SJ';
DROP TABLE IF EXISTS occurrence_record_SK;
CREATE TABLE occurrence_record_SK SELECT * FROM occurrence_record WHERE iso_country_code='SK';
DROP TABLE IF EXISTS occurrence_record_SL;
CREATE TABLE occurrence_record_SL SELECT * FROM occurrence_record WHERE iso_country_code='SL';
DROP TABLE IF EXISTS occurrence_record_SM;
CREATE TABLE occurrence_record_SM SELECT * FROM occurrence_record WHERE iso_country_code='SM';
DROP TABLE IF EXISTS occurrence_record_SN;
CREATE TABLE occurrence_record_SN SELECT * FROM occurrence_record WHERE iso_country_code='SN';
DROP TABLE IF EXISTS occurrence_record_SO;
CREATE TABLE occurrence_record_SO SELECT * FROM occurrence_record WHERE iso_country_code='SO';
DROP TABLE IF EXISTS occurrence_record_SR;
CREATE TABLE occurrence_record_SR SELECT * FROM occurrence_record WHERE iso_country_code='SR';
DROP TABLE IF EXISTS occurrence_record_ST;
CREATE TABLE occurrence_record_ST SELECT * FROM occurrence_record WHERE iso_country_code='ST';
DROP TABLE IF EXISTS occurrence_record_SV;
CREATE TABLE occurrence_record_SV SELECT * FROM occurrence_record WHERE iso_country_code='SV';
DROP TABLE IF EXISTS occurrence_record_SY;
CREATE TABLE occurrence_record_SY SELECT * FROM occurrence_record WHERE iso_country_code='SY';
DROP TABLE IF EXISTS occurrence_record_SZ;
CREATE TABLE occurrence_record_SZ SELECT * FROM occurrence_record WHERE iso_country_code='SZ';
DROP TABLE IF EXISTS occurrence_record_TC;
CREATE TABLE occurrence_record_TC SELECT * FROM occurrence_record WHERE iso_country_code='TC';
DROP TABLE IF EXISTS occurrence_record_TD;
CREATE TABLE occurrence_record_TD SELECT * FROM occurrence_record WHERE iso_country_code='TD';
DROP TABLE IF EXISTS occurrence_record_TF;
CREATE TABLE occurrence_record_TF SELECT * FROM occurrence_record WHERE iso_country_code='TF';
DROP TABLE IF EXISTS occurrence_record_TG;
CREATE TABLE occurrence_record_TG SELECT * FROM occurrence_record WHERE iso_country_code='TG';
DROP TABLE IF EXISTS occurrence_record_TH;
CREATE TABLE occurrence_record_TH SELECT * FROM occurrence_record WHERE iso_country_code='TH';
DROP TABLE IF EXISTS occurrence_record_TJ;
CREATE TABLE occurrence_record_TJ SELECT * FROM occurrence_record WHERE iso_country_code='TJ';
DROP TABLE IF EXISTS occurrence_record_TK;
CREATE TABLE occurrence_record_TK SELECT * FROM occurrence_record WHERE iso_country_code='TK';
DROP TABLE IF EXISTS occurrence_record_TL;
CREATE TABLE occurrence_record_TL SELECT * FROM occurrence_record WHERE iso_country_code='TL';
DROP TABLE IF EXISTS occurrence_record_TM;
CREATE TABLE occurrence_record_TM SELECT * FROM occurrence_record WHERE iso_country_code='TM';
DROP TABLE IF EXISTS occurrence_record_TN;
CREATE TABLE occurrence_record_TN SELECT * FROM occurrence_record WHERE iso_country_code='TN';
DROP TABLE IF EXISTS occurrence_record_TO;
CREATE TABLE occurrence_record_TO SELECT * FROM occurrence_record WHERE iso_country_code='TO';
DROP TABLE IF EXISTS occurrence_record_TR;
CREATE TABLE occurrence_record_TR SELECT * FROM occurrence_record WHERE iso_country_code='TR';
DROP TABLE IF EXISTS occurrence_record_TT;
CREATE TABLE occurrence_record_TT SELECT * FROM occurrence_record WHERE iso_country_code='TT';
DROP TABLE IF EXISTS occurrence_record_TV;
CREATE TABLE occurrence_record_TV SELECT * FROM occurrence_record WHERE iso_country_code='TV';
DROP TABLE IF EXISTS occurrence_record_TW;
CREATE TABLE occurrence_record_TW SELECT * FROM occurrence_record WHERE iso_country_code='TW';
DROP TABLE IF EXISTS occurrence_record_TZ;
CREATE TABLE occurrence_record_TZ SELECT * FROM occurrence_record WHERE iso_country_code='TZ';
DROP TABLE IF EXISTS occurrence_record_UA;
CREATE TABLE occurrence_record_UA SELECT * FROM occurrence_record WHERE iso_country_code='UA';
DROP TABLE IF EXISTS occurrence_record_UG;
CREATE TABLE occurrence_record_UG SELECT * FROM occurrence_record WHERE iso_country_code='UG';
DROP TABLE IF EXISTS occurrence_record_UM;
CREATE TABLE occurrence_record_UM SELECT * FROM occurrence_record WHERE iso_country_code='UM';
DROP TABLE IF EXISTS occurrence_record_US;
CREATE TABLE occurrence_record_US SELECT * FROM occurrence_record WHERE iso_country_code='US';
DROP TABLE IF EXISTS occurrence_record_UY;
CREATE TABLE occurrence_record_UY SELECT * FROM occurrence_record WHERE iso_country_code='UY';
DROP TABLE IF EXISTS occurrence_record_UZ;
CREATE TABLE occurrence_record_UZ SELECT * FROM occurrence_record WHERE iso_country_code='UZ';
DROP TABLE IF EXISTS occurrence_record_VA;
CREATE TABLE occurrence_record_VA SELECT * FROM occurrence_record WHERE iso_country_code='VA';
DROP TABLE IF EXISTS occurrence_record_VC;
CREATE TABLE occurrence_record_VC SELECT * FROM occurrence_record WHERE iso_country_code='VC';
DROP TABLE IF EXISTS occurrence_record_VE;
CREATE TABLE occurrence_record_VE SELECT * FROM occurrence_record WHERE iso_country_code='VE';
DROP TABLE IF EXISTS occurrence_record_VG;
CREATE TABLE occurrence_record_VG SELECT * FROM occurrence_record WHERE iso_country_code='VG';
DROP TABLE IF EXISTS occurrence_record_VI;
CREATE TABLE occurrence_record_VI SELECT * FROM occurrence_record WHERE iso_country_code='VI';
DROP TABLE IF EXISTS occurrence_record_VN;
CREATE TABLE occurrence_record_VN SELECT * FROM occurrence_record WHERE iso_country_code='VN';
DROP TABLE IF EXISTS occurrence_record_VU;
CREATE TABLE occurrence_record_VU SELECT * FROM occurrence_record WHERE iso_country_code='VU';
DROP TABLE IF EXISTS occurrence_record_WF;
CREATE TABLE occurrence_record_WF SELECT * FROM occurrence_record WHERE iso_country_code='WF';
DROP TABLE IF EXISTS occurrence_record_WS;
CREATE TABLE occurrence_record_WS SELECT * FROM occurrence_record WHERE iso_country_code='WS';
DROP TABLE IF EXISTS occurrence_record_YE;
CREATE TABLE occurrence_record_YE SELECT * FROM occurrence_record WHERE iso_country_code='YE';
DROP TABLE IF EXISTS occurrence_record_YT;
CREATE TABLE occurrence_record_YT SELECT * FROM occurrence_record WHERE iso_country_code='YT';
DROP TABLE IF EXISTS occurrence_record_ZA;
CREATE TABLE occurrence_record_ZA SELECT * FROM occurrence_record WHERE iso_country_code='ZA';
DROP TABLE IF EXISTS occurrence_record_ZM;
CREATE TABLE occurrence_record_ZM SELECT * FROM occurrence_record WHERE iso_country_code='ZM';
DROP TABLE IF EXISTS occurrence_record_ZW;
CREATE TABLE occurrence_record_ZW SELECT * FROM occurrence_record WHERE iso_country_code='ZW';
